name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.tool-versions'
        cache: 'npm'
    - name: Install modules
      run: npm ci
    - name: Check generated artifacts
      run: npm run check:artifacts
    - name: Build distribution
      run: npm run build
    - name: Run tests
      run: npm test
